// This source code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © relevantLeader16058

// Tested on: BTCUSDT 30min
// https://github.com/Alorse/pinescript-strategies/blob/master/strategies/BB%20%2B%20Aroon.pine

//@version=5
strategy(
     title='Bollinger bands + Aroon [Alorse]', 
     shorttitle='BB + Aroon [Alorse]', 
     overlay=true, 
     pyramiding=0, 
     initial_capital=1000,
     currency=currency.USD, 
     default_qty_type=strategy.percent_of_equity, 
     default_qty_value=100, 
     commission_type=strategy.commission.percent, 
     commission_value=0.1
     )

// BB inputs and calculations
lengthBB = input.int(20, minval=1)
src = input(close, title='Source')
mult = input.float(2.0, minval=0.001, maxval=50, title='StdDev')
basis = ta.sma(src, lengthBB)
dev = mult * ta.stdev(src, lengthBB)
upper = basis + dev
lower = basis - dev


lengthAr = input.int(288, minval=1)
AroonUP = 100 * (ta.highestbars(high, lengthAr + 1) + lengthAr) / lengthAr
AroonDown = 100 * (ta.lowestbars(low, lengthAr + 1) + lengthAr) / lengthAr


Confirmation = input(90, 'Aroon Confirmation')
Stop = input(70, 'Aroon Stop')

Bullish = ta.crossunder(close, lower)
Bearish = ta.crossunder(close, upper)

// ====== ORDERS ======

// LIVEMODE:: ENABLE / DISABLE
enableLiveTest = input.bool(false, title="Enable live mode and stop backtesting", group="Livemode / Backtesting")
curDate = timestamp('2023, 08, 06')
targetDate = input.time(curDate, title="Start live mode from:", group="Livemode / Backtesting")
// LIVEMODE:: END

if enableLiveTest == false or time > targetDate
    
    // Long
    if Bullish and AroonUP > Confirmation
        strategy.entry('Long', strategy.long)

    if Bearish or AroonUP < Stop
        strategy.close('Long')


    // Short
    if Bearish and AroonDown > Confirmation
        strategy.entry('Short', strategy.short)

    if Bullish or AroonDown < Stop
        strategy.close('Short')
