// Good results tested with: BTCUSDT 30min

// ChartArt's RSI + Bollinger Bands, Double Strategy UPDATE: Long-Only
//
// Version 1.2
// Idea by ChartArt on October 4, 2017.
//
// This strategy uses the RSI indicator 
// together with the Bollinger Bands 
// to buy when the price is below the
// lower Bollinger Band (and to close the
// long trade when this value is above
// the upper Bollinger band).
//
// This simple strategy only longs when
// both the RSI and the Bollinger Bands
// indicators are at the same time in
// a oversold condition.
//
// In this new version 1.2 the strategy was
// simplified by going long-only, which made
// it more successful in backtesting. 
//
// List of my work: 
// https://www.tradingview.com/u/ChartArt/
// 
//  __             __  ___       __  ___ 
// /  ` |__|  /\  |__)  |   /\  |__)  |  
// \__, |  | /~~\ |  \  |  /~~\ |  \  |  
// 
// 
//@version=5

strategy('Bollinger + RSI, Double Strategy Long-Only (by ChartArt) v1.2', commission_value=0.055, shorttitle='CA_-_RSI_Bol_Strat_1.2', initial_capital=100, slippage=3, overlay=true)

///////////// RSI
RSIlength = input(6, title='RSI Period Length')
RSIoverSold = 50
RSIoverBought = 50
price = close
vrsi = ta.rsi(price, RSIlength)


///////////// Bollinger Bands
BBlength = input.int(200, minval=1, title='Bollinger Period Length')
BBmult = 2  // input(2.0, minval=0.001, maxval=50,title="Bollinger Bands Standard Deviation")
BBbasis = ta.sma(price, BBlength)
BBdev = BBmult * ta.stdev(price, BBlength)
BBupper = BBbasis + BBdev
BBlower = BBbasis - BBdev
source = close
buyEntry = ta.crossover(source, BBlower)
sellEntry = ta.crossunder(source, BBupper)
plot(BBbasis, color=color.new(color.aqua, 0), title='Bollinger Bands SMA Basis Line')
p1 = plot(BBupper, color=color.new(color.silver, 0), title='Bollinger Bands Upper Line')
p2 = plot(BBlower, color=color.new(color.silver, 0), title='Bollinger Bands Lower Line')
fill(p1, p2, transp=90)


///////////// Colors
switch1 = input(true, title='Enable Bar Color?')
switch2 = input(true, title='Enable Background Color?')
TrendColor = RSIoverBought and price[1] > BBupper and price < BBupper and BBbasis < BBbasis[1] ? color.red : RSIoverSold and price[1] < BBlower and price > BBlower and BBbasis > BBbasis[1] ? color.green : na
barcolor(switch1 ? TrendColor : na)
bgcolor(switch2 ? TrendColor : na, transp=50)


///////////// RSI + Bollinger Bands Strategy
long = ta.crossover(vrsi, RSIoverSold) and ta.crossover(source, BBlower)
close_long = ta.crossunder(vrsi, RSIoverBought) and ta.crossunder(source, BBupper)

// LIVEMODE:: ENABLE / DISABLE
enableLiveTest = input.bool(false, title="Enable live mode and stop backtesting", group="Livemode / Backtesting")
curDate = timestamp('2023, 08, 06')
targetDate = input.time(curDate, title="Start live mode from:", group="Livemode / Backtesting")
// LIVEMODE:: END

if enableLiveTest == false or time > targetDate
    if not na(vrsi)

        if long
            strategy.entry('RSI_BB', strategy.long, stop=BBlower, oca_type=strategy.oca.cancel, comment='RSI_BB')
        else
            strategy.cancel(id='RSI_BB')

        if close_long
            strategy.close('RSI_BB')


//plot(strategy.equity, title="equity", color=red, linewidth=2, style=areabr)

