//@version=5 

strategy(title='ETH APO Strategy', shorttitle='ETH APO Strategy', initial_capital=1000, currency=currency.USD, overlay=false)

LengthShortEMA = input.int(9, minval=1)
LengthLongEMA = input.int(19, minval=1)
hline(0, color=color.gray, linestyle=hline.style_dotted)
upperBand = hline(15, color=color.gray, linestyle=hline.style_dashed)
lowerBand = hline(-15, color=color.gray, linestyle=hline.style_dashed)
fill(upperBand, lowerBand, color=color.rgb(126, 87, 194, 90), title="RSI Background Fill")
xPrice = close
xShortEMA = ta.ema(xPrice, LengthShortEMA)
xLongEMA = ta.ema(xPrice, LengthLongEMA)
xAPO = xShortEMA - xLongEMA
plot(xAPO, color=color.yellow, title="APO")


up = ta.rma(math.max(ta.change(close), 0), 14)
down = ta.rma(-math.min(ta.change(close), 0), 14)
rsi = down == 0 ? 100 : up == 0 ? 0 : 100 - (100 / (1 + up / down))
rsiMA = ta.sma(rsi, 5)

// LIVEMODE:: ENABLE / DISABLE
enableLiveTest = input.bool(false, title="Enable live mode and stop backtesting", group="Livemode / Backtesting")
curDate = timestamp('2023, 08, 06')
targetDate = input.time(curDate, title="Start live mode from:", group="Livemode / Backtesting")
// LIVEMODE:: END

if enableLiveTest == false or time > targetDate
    if ta.crossover(xAPO, -15) and rsiMA > rsiMA[2]
        strategy.entry("LONG", strategy.long)

    if ta.crossover(xAPO, 14) or ta.crossunder(rsiMA, 70) or ta.crossunder(rsiMA, 60) or ta.crossunder(rsiMA, 25)
        strategy.close_all()

