// PLEASE BE CAREFULL, THIS SCRIPT REPAINTS

//@version=5
strategy('Japo v1 [Alorse]', shorttitle='Japo [Alorse]', overlay=true, pyramiding=0, currency=currency.USD, default_qty_type=strategy.percent_of_equity, initial_capital=1000, default_qty_value=50, commission_type=strategy.commission.percent, commission_value=0.1)

res = input.timeframe(title="Heikin Ashi Candle Timeframe", defval="60")
hshift = input(1, title="Heikin Ashi Candle Timeframe Shift")
res1 = input.timeframe(title="Heikin Ashi Candle Timeframe", defval="180")
mshift = input(0, title="Heikin Ashi EMA timeframe Shift")
fama = input(1, title="Heikin Ashi EMA Periods")
test = input(1, title="Heikin Ashi EMA Shift")
sloma = input(30, title="Slow EMA Periods")
slomas = input(1, title="Slow  EMA Shift")

// Heikin Ashi Open/Close price
ha_t = ticker.heikinashi(syminfo.tickerid)

ha_close = request.security(ha_t, res, close[hshift], lookahead=barmerge.lookahead_on)
mha_close = request.security(ha_t, res1, close[mshift], lookahead=barmerge.lookahead_on)

// EMAs
fma = ta.ema(mha_close[test], fama)
sma = ta.ema(mha_close[slomas], sloma)
plot(fma, title="MA", color=color.lime, linewidth=2, style=plot.style_line)
plot(sma, title="SMA", color=color.red, linewidth=2, style=plot.style_line)

// Strategy
golong = ta.crossover(fma,sma)
goshort = ta.crossunder(fma,sma)

// LIVEMODE:: ENABLE / DISABLE
enableLiveTest = input.bool(false, title="Enable live mode and stop backtesting", group="Livemode / Backtesting")
curDate = timestamp('2023, 08, 06')
targetDate = input.time(curDate, title="Start live mode from:", group="Livemode / Backtesting")
// LIVEMODE:: END

if enableLiveTest == false or time > targetDate
    strategy.entry("Long", strategy.long, when=golong)
    strategy.entry("Short", strategy.short, when=goshort)