//@version=5

// Found: on TV
// Tested: with XRPUSDT | 30min
// Results: 78% | 3.5

strategy('Kozlod - BB Strategy - 1 minute', overlay=true, default_qty_type=strategy.percent_of_equity, default_qty_value=5)

source = close
length = input.int(45, minval=1)
mult = input.float(2.5, minval=0.001, maxval=50)

basis = ta.sma(source, length)
dev = mult * ta.stdev(source, length)

upper = basis + dev
lower = basis - dev

plot(upper)
plot(lower)

buyEntry = ta.crossover(source, lower)
sellEntry = ta.crossunder(source, upper)

// LIVEMODE:: ENABLE / DISABLE
enableLiveTest = input.bool(false, title="Enable live mode and stop backtesting", group="Livemode / Backtesting")
curDate = timestamp('2023, 08, 06')
targetDate = input.time(curDate, title="Start live mode from:", group="Livemode / Backtesting")
// LIVEMODE:: END

if enableLiveTest == false or time > targetDate
    if ta.crossover(source, lower)
        strategy.entry('BBandLE', strategy.long, stop=lower, oca_name='BollingerBands', oca_type=strategy.oca.cancel, comment='BBandLE')
    else
        strategy.cancel(id='BBandLE')

    if ta.crossunder(source, upper)
        strategy.entry('BBandSE', strategy.short, stop=upper, oca_name='BollingerBands', oca_type=strategy.oca.cancel, comment='BBandSE')
    else
        strategy.cancel(id='BBandSE')

