//@version=5

strategy(
           title='Martingale',
           calc_on_order_fills=true,
           calc_on_every_tick=false,
           initial_capital=100,
           commission_type=strategy.commission.percent,
           commission_value=0.055,
           overlay=true,
           slippage=3,
           default_qty_type=strategy.percent_of_equity,
           default_qty_value=100)

buffer = input.float(title='buffer', defval=0.2, minval=0, step=0.1)
stop_loss = input.int(15, 'Stop loss %', minval=1, step=1)
Target_profit = input.int(15, 'Target Profit %', minval=1, step=1)

b1 = close[1] * (1 + buffer / 100)
b2 = close[1] * (1 - buffer / 100)

// LIVEMODE:: ENABLE / DISABLE
enableLiveTest = input.bool(false, title="Enable live mode and stop backtesting", group="Livemode / Backtesting")
curDate = timestamp('2023, 08, 06')
targetDate = input.time(curDate, title="Start live mode from:", group="Livemode / Backtesting")
// LIVEMODE:: END

if enableLiveTest == false or time > targetDate
    strategy.entry('Long', strategy.long, when=close > b1, comment='entry')
    strategy.close('Long', when=close < b2, comment='exit')
    //money management
    sl = strategy.position_avg_price * (1 - stop_loss / 100)
    close_Stop = close < sl
    strategy.close('Long', when=close_Stop, comment='Stop loss')
    tp = strategy.position_avg_price * (1 + Target_profit / 100)
    close_Target = close > tp
    strategy.close('Long', when=close_Target, comment='Target')