//@version=5

strategy(
           title='Martingale',
           calc_on_order_fills=true,
           calc_on_every_tick=false,
           initial_capital=100,
           commission_type=strategy.commission.percent,
           commission_value=0.055,
           overlay=true,
           slippage=3,
           default_qty_type=strategy.percent_of_equity,
           default_qty_value=100)

direction = input.string("Long", "Direction", options= ['Long', 'Short'])
buffer = input.float(title='buffer', defval=0.2, minval=0, step=0.1)
stop_loss = input.int(15, 'Stop loss %', minval=1, step=1)
Target_profit = input.int(15, 'Target Profit %', minval=1, step=1)

b1 = close[1] * (1 + buffer / 100)
b2 = close[1] * (1 - buffer / 100)

// LIVEMODE:: ENABLE / DISABLE
enableLiveTest = input.bool(false, title="Enable live mode and stop backtesting", group="Livemode / Backtesting")
curDate = timestamp('2023, 08, 06')
targetDate = input.time(curDate, title="Start live mode from:", group="Livemode / Backtesting")
// LIVEMODE:: END

enterLong = close > b1
exitLong = close < b2


sl = strategy.position_avg_price * (1 - stop_loss / 100)
close_Stop = close < sl

tp = strategy.position_avg_price * (1 + Target_profit / 100)
close_Target = close > tp

if enableLiveTest == false or time > targetDate

    if direction == "Long"
        if enterLong
            strategy.entry('Long', strategy.long)

        if exitLong
            strategy.close('Long')

        if close_Stop
            strategy.close('Long', comment='Stop loss')
        
        if close_Target
            strategy.close('Long', comment='Target')

    if direction == "Short"
        if exitLong
            strategy.entry('Short', strategy.short)

        if enterLong
            strategy.close('Short')

        if close_Stop
            strategy.close('Short', comment='Target')
        
        if close_Target
            strategy.close('Short', comment='Stop loss')
