//@version=5
// Copyright all rights reserved to DaviddTech
strategy('RSI Divergence + EMA400', overlay=true, precision=3, calc_on_every_tick=false, calc_on_order_fills=false, default_qty_type=strategy.percent_of_equity, commission_value=0.05, commission_type=strategy.commission.percent, slippage=1, currency=currency.USD, default_qty_value=5, max_bars_back=3000, initial_capital=100000
 ,pyramiding=2,default_qty_type=strategy.fixed)
// pyramiding=2,default_qty_value=2,   default_qty_type=strategy.fixed, initial_capital=10000, currency=currency.USD

// SOURCE: https://www.youtube.com/watch?v=wy_Nv8JSg6Y&t=13s
// SOURCE CODE https://www.tradingview.com/script/qSLcZSyw-RSI-Divergence-Indicator-strategy/
// Timeframe 30m(!)


// ****************************************************************************//
// ---------------------------------> Edit here ------------------------------ //
// ****************************************************************************//

//strategy(title="RSI Divergence Indicator", overlay=false,pyramiding=2, default_qty_value=2,   default_qty_type=strategy.fixed, initial_capital=10000, currency=currency.USD)
//GOOGL setting  5 , close, 3 , 1  profitLevel at 75 shows win rate  87.21 %  profit factor 7.059
//GOOGL setting  8 , close, 3 , 1  profitLevel at 80 shows win rate  86.57 %  profit factor 18.96
//SPY setting    5, close , 3, 3  profitLevel at 70  , shows win rate 80.34%  profit factor 2.348

isStrategyPlot = input.bool(true, "Plot strategy indicators(except oscillators)", group='Strategy: base')
stratRSILen = input.int(title="RSI Period", minval=1, defval=9, group='Strategy: base')
stratSrc = input.source(title="RSI Source", defval=close, group='Strategy: base')
stratLbR = input.int(title="Pivot Lookback Right", defval=3, group='Strategy: base')
stratLbL = input.int(title="Pivot Lookback Left", defval=1, group='Strategy: base')
stratTPRSILevel = input.int(title="Long Take Profit at RSI Level", minval=70, defval=80, group='Strategy: base')
stratTPShortRSILevel = input.int(title="Short Take Profit at RSI Level", minval=30, defval=20, group='Strategy: base')


stratRangeUpper = input.int(title="Max of Lookback Range", defval=60, group='Strategy: base')
stratRangeULower = input.int(title="Min of Lookback Range", defval=5, group='Strategy: base')

stratSLType = input.string("NONE", title="Trailing StopLoss Type", options=['ATR','PERC', 'NONE'], group='Strategy: base')
stratSLLevel = input.int(title="Stop Loss%", defval=5, minval=1, group='Strategy: base')
stratAtrLen=input.int(14, title="ATR Length (for Trailing stop loss)", group='Strategy: base')
stratAtrMultiplier=input.float(3.5, title="ATR Multiplier (for Trailing stop loss)", group='Strategy: base')

stratIsUseEMA=input.bool(true, title="Use EMA Length for Trend Confirmation?", group='Strategy: base')
stratEMATf = input.timeframe('240', "Resolution (min)", options=['120','240','1D'], group='Strategy: base')
stratEMALen=input.int(200, title="EMA Length (for trend confirmation)", group='Strategy: base')

isEnterToShort = input.bool(title="Enter to short?", defval=false, group='Strategy: base')

isPlotBull = input.bool(title="Plot Bullish", defval=true, group='Strategy: base')
isPlotHiddenBull = input.bool(title="Plot Hidden Bullish", defval=true, group='Strategy: base')
isPlotBear = input.bool(title="Plot Bearish", defval=true, group='Strategy: base')
isPlotHiddenBear = input.bool(title="Plot Hidden Bearish", defval=false, group='Strategy: base')

//useTrailStopLoss = input(false, title="Use Trailing Stop Loss")




bearColor = color.purple
bullColor = color.green
hiddenBullColor = color.new(color.green, 80)
hiddenBearColor = color.new(color.red, 80)
textColor = color.white
noneColor = color.new(color.white, 100)

stratRSI = ta.rsi(stratSrc, stratRSILen)

stratEMA = request.security(syminfo.tickerid, stratEMATf, ta.ema(stratSrc, stratEMALen))
isEMAUpTrend = stratEMA>stratEMA[1]

plot(isStrategyPlot ? stratRSI: na, title="RSI", linewidth=2, color=#8D1699)
hline(isStrategyPlot ?50 : na, title="Middle Line", linestyle=hline.style_dotted)
obLevel = hline(isStrategyPlot? 70: na, title="Overbought", linestyle=hline.style_dotted)
osLevel = hline(isStrategyPlot ? 30:na, title="Oversold", linestyle=hline.style_dotted)
fill(obLevel, osLevel, title="Background", color=#9915FF, transp=90)

isPlFound = na(ta.pivotlow(stratRSI, stratLbL, stratLbR)) ? false : true
isPhFound = na(ta.pivothigh(stratRSI, stratLbL, stratLbR)) ? false : true

_inRange(cond) =>
    bars = ta.barssince(cond == true)
    stratRangeULower <= bars and bars <= stratRangeUpper

//------------------------------------------------------------------------------
// Regular Bullish

// stratRSI: Higher Low
stratRSIHL = stratRSI[stratLbR] > ta.valuewhen(isPlFound, stratRSI[stratLbR], 1) and _inRange(isPlFound[1])

// Price: Lower Low
priceLL = low[stratLbR] < ta.valuewhen(isPlFound, low[stratLbR], 1)

// isBullCond = isPlotBull and priceLL and stratRSIHL and isPlFound // SOURCE VERSION
isBullCond = priceLL and stratRSIHL and isPlFound

plot(isStrategyPlot and isPlFound and isPlotBull ? stratRSI[stratLbR] : na, offset=-stratLbR, title="Regular Bullish", linewidth=2, color=(isBullCond ? bullColor : noneColor))


plotshape(isStrategyPlot and isBullCond ? stratRSI[stratLbR] : na, offset=-stratLbR, title="Regular Bullish Label", text=" Bull ", style=shape.labelup, location=location.absolute, color=bullColor, textcolor=textColor)

//------------------------------------------------------------------------------
// Hidden Bullish

// stratRSI: Lower Low
stratRSILL = stratRSI[stratLbR] < ta.valuewhen(isPlFound, stratRSI[stratLbR], 1) and _inRange(isPlFound[1])

// Price: Higher Low
priceHL = low[stratLbR] > ta.valuewhen(isPlFound, low[stratLbR], 1)

// isHiddenBullCond = isPlotHiddenBull and priceHL and stratRSILL and isPlFound // SOURCE VERSION
isHiddenBullCond = priceHL and stratRSILL and isPlFound

plot(isStrategyPlot and isPlFound and isPlotHiddenBull? stratRSI[stratLbR] : na, offset=-stratLbR, title="Hidden Bullish", linewidth=2, color=(isHiddenBullCond ? hiddenBullColor : noneColor))

plotshape(isStrategyPlot and isHiddenBullCond ? stratRSI[stratLbR] : na, offset=-stratLbR, title="Hidden Bullish Label", text=" H Bull ", style=shape.labelup, location=location.absolute, color=bullColor, textcolor=textColor)


//Trailing StopLoss
////// Calculate trailing SL
/////////////////////////////////////////////////////
stratSLVal = stratSLType == "ATR"      ? stratSLLevel * ta.atr(stratAtrLen) :
         stratSLType == "PERC" ? close * stratSLLevel / 100 : 0.00

stratTrailingSL = 0.0
stratTrailingSL := strategy.position_size>=1 ?  math.max(low  - stratSLVal, nz(stratTrailingSL[1])) :  na
stratShortTrailingSL = 0.0
stratShortTrailingSL := strategy.position_size<=1 ?  math.min(high + stratSLVal, nz(stratTrailingSL[1])) :  na

//draw initil stop loss
//plot(strategy.position_size>=1 ? stratTrailingSL : na, color = color.blue , style=plot.style_linebr,  linewidth = 2, title = "stop loss")
//plot(stratTrailingSL, title="ATR Trailing Stop Loss", style=plot.style_linebr, linewidth=1, color=color.purple, transp=30)
//Trailing StopLoss
////// Calculate trailing SL
/////////////////////////////////////////////////////


//------------------------------------------------------------------------------
// Regular Bearish

// stratRSI: Lower High
stratRSILH = stratRSI[stratLbR] < ta.valuewhen(isPhFound, stratRSI[stratLbR], 1) and _inRange(isPhFound[1])

// Price: Higher High
priceHH = high[stratLbR] > ta.valuewhen(isPhFound, high[stratLbR], 1)

// isBearCond = isPlotBear and priceHH and stratRSILH and isPhFound // Source version
isBearCond = priceHH and stratRSILH and isPhFound

plot(isStrategyPlot and isPhFound and  isPlotBear ? stratRSI[stratLbR] : na, offset=-stratLbR, title="Regular Bearish", linewidth=2, color=(isBearCond ? bearColor : noneColor))

plotshape(isStrategyPlot and isBearCond ? stratRSI[stratLbR] : na, offset=-stratLbR, title="Regular Bearish Label", text=" Bear ", style=shape.labeldown, location=location.absolute, color=bearColor, textcolor=textColor)

//------------------------------------------------------------------------------
// Hidden Bearish

// stratRSI: Higher High
stratRSIHH = stratRSI[stratLbR] > ta.valuewhen(isPhFound, stratRSI[stratLbR], 1) and _inRange(isPhFound[1])

// Price: Lower High
priceLH = high[stratLbR] < ta.valuewhen(isPhFound, high[stratLbR], 1)

// isHiddenBearCond = isPlotHiddenBear and priceLH and stratRSIHH and isPhFound // Source
isHiddenBearCond = priceLH and stratRSIHH and isPhFound

plot(isStrategyPlot and isPhFound and isPlotHiddenBear? stratRSI[stratLbR] : na, offset=-stratLbR, title="Hidden Bearish", linewidth=2, color=(isHiddenBearCond ? hiddenBearColor : noneColor))

plotshape(isStrategyPlot and isHiddenBearCond ? stratRSI[stratLbR] : na, offset=-stratLbR, title="Hidden Bearish Label", text=" H Bear ", style=shape.labeldown, location=location.absolute, color=bearColor, textcolor=textColor)


// STRATEGY ENTRY
enter_long=(isBullCond or isHiddenBullCond) and (not stratIsUseEMA or isEMAUpTrend)
strategy.entry(id="RSIDivLE", direction=strategy.long, when=enter_long)

enter_short=isEnterToShort and (isBearCond or isHiddenBearCond) and (not stratIsUseEMA or not isEMAUpTrend)
strategy.entry(id="RSIDivLEShort", direction=strategy.short, when=enter_short)

longCloseCondition=ta.crossover(stratRSI, stratTPRSILevel) or isBearCond
isLongTakeProfit = math.abs(strategy.position_size)>=1 and stratSLType == "NONE" and longCloseCondition
isLongStopLoss =math.abs(strategy.position_size)>=1 and (stratSLType == "PERC" or stratSLType == "ATR") and ta.crossunder(close, stratTrailingSL)
strategy.close(id="RSIDivLE", comment="Close All="+str.tostring(close - strategy.position_avg_price, "####.##"), when=isLongStopLoss)
//close all on stop loss
strategy.close(id="RSIDivLE", comment="TSL="+str.tostring(close - strategy.position_avg_price, "####.##"),  when=isLongTakeProfit)  //close<ema55 and rsi5Val<20 //ema34<ema55  //close<ema89


shortCloseCondition=ta.crossunder(stratRSI, stratTPShortRSILevel) or isBullCond
isShortTakeProfit = math.abs(strategy.position_size)>=1 and stratSLType == "NONE" and shortCloseCondition
isShortStopLoss =math.abs(strategy.position_size)>=1 and (stratSLType == "PERC" or stratSLType == "ATR") and ta.crossover(close, stratShortTrailingSL)
// strategy.close(id="RSIDivLEShort", comment="Close All="+str.tostring(close - strategy.position_avg_price, "####.##"), when=isShortTakeProfit)
//close all on stop loss
// strategy.close(id="RSIDivLEShort", comment="TSL="+str.tostring(close - strategy.position_avg_price, "####.##"),  when=isShortStopLoss)  //close<ema55 and rsi5Val<20 //ema34<ema55  //close<ema89


force_exit_signal_short = false
force_exit_signal_long = false

// Dashboard lights
_take_long_one = isBullCond
_take_long_two = isHiddenBullCond
_take_long_three = enter_long

_take_short_one = isBearCond
_take_short_two = isHiddenBearCond
_take_short_three = enter_short



