//@author impressive_Snow
//@version=5

strategy(
	 title='webhook test', 
	 overlay=true, 
	 initial_capital=100,
	 default_qty_type=strategy.percent_of_equity, 
     default_qty_value=100,
	 commission_value=0.055
	 )

// ---INPUTS---
toTest     =   input.string("long/short", "what are you testing", options= ['long/short', 'order', 'exitAll'])
// ------------

hasPosition = strategy.position_size != 0
intervalInMinutes =  1

even = barstate.isrealtime and minute(time) % (intervalInMinutes + intervalInMinutes) < intervalInMinutes
uneven = barstate.isrealtime and minute(time) % (intervalInMinutes + intervalInMinutes) >= intervalInMinutes

var const_i = 1
message = '"i": "' + str.tostring(const_i) + '"'

// ---ORDERS---
if even
    if toTest == "long/short"
        const_i := const_i + 1
        strategy.entry('Long', strategy.long, alert_message = message)

    if toTest == "order"
        const_i := const_i + 1
        strategy.order('Long', strategy.long, alert_message = message)

        if hasPosition
            // strategy.exit("Exit Short", from_entry="Long", limit=low * 0.90)
            // strategy.close("Exit", "Long")
            strategy.close_all()

if uneven
    if toTest == "long/short"
        const_i := const_i + 1
        strategy.entry('Short', strategy.short, alert_message = message)

    if toTest == "order"
        const_i := const_i + 1
        strategy.order('Long', strategy.long, alert_message = message)
// ------------
