// This source code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © tradingmaestro12

//@version=5

library("Strategy", overlay = true)



// SESSION TIMES
// ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░



// @function is_allowed_day_in_week
// @param bool mo
// @param bool tu
// @param bool we
// @param bool th
// @param bool fr
// @param bool sa
// @param bool su
// @return bool
export is_allowed_day_in_week (bool mo, bool tu, bool we, bool th, bool fr, bool sa, bool su) =>
	dayofweek(time) == dayofweek.monday and mo or
	 dayofweek(time) == dayofweek.tuesday and tu or
	 dayofweek(time) == dayofweek.wednesday and we or
	 dayofweek(time) == dayofweek.thursday and th or
	 dayofweek(time) == dayofweek.friday and fr or
	 dayofweek(time) == dayofweek.saturday and sa or
	 dayofweek(time) == dayofweek.sunday and su



// @function is_active_session
// @param bool is_live_mode
// @param int target_date
// @return bool
export is_active_session (bool is_live_mode, int target_date ) =>
	is_live_mode == false or time > target_date



// @function is_flat_market
// @param int avg_price
// @param int percentage
// @param series float bar_type
// @return float
export is_flat_market (int avg_price = 100, int percentage = 1, series float bar_type = close) =>
	sma_avgPrice = ta.sma(bar_type, avg_price)
	math.abs(bar_type - sma_avgPrice) <= (sma_avgPrice * percentage / 100)

// ORDERS
// ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░



// @function in_long_position
// @return bool
export in_long_position () =>
	strategy.position_size > 0 



// @function in_long_position
// @return bool
export in_short_position () =>
	strategy.position_size < 0



// @function in_position
// @return bool
export in_position () =>
	in_long_position() or in_short_position()
